export const USER_LOGIN_REQEUST = 'USER_LOGIN_REQEUST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'


export const USER_REGISTER_REQEUST = 'USER_REGISTER_REQEUST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQEUST = 'USER_DETAILS_REQEUST'
export const USER_DETAILS_SUCCESS = 'USER_DETAIL_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'


export const USER_UPDATE_PROFILE_REQEUST = 'USER_UPDATE_PROFILE_REQEUST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

